export const devicesByStateData = [
  {
    name: 'São Paulo',
    region: 'Southeast',
    devices: {
      desktops: 6200,
      laptops: 7800,
      smartphones: 3800,
      tablets: 700,
      total: 18500,
    },
  },
  {
    name: 'Minas Gerais',
    region: 'Southeast',
    devices: {
      desktops: 2800,
      laptops: 3500,
      smartphones: 1800,
      tablets: 500,
      total: 8600,
    },
  },
  {
    name: 'Rio de Janeiro',
    region: 'Southeast',
    devices: {
      desktops: 2300,
      laptops: 3100,
      smartphones: 1400,
      tablets: 300,
      total: 7100,
    },
  },
  {
    name: 'Bahia',
    region: 'Northeast',
    devices: {
      desktops: 1800,
      laptops: 2500,
      smartphones: 1200,
      tablets: 400,
      total: 5900,
    },
  },
  {
    name: 'Paraná',
    region: 'South',
    devices: {
      desktops: 1500,
      laptops: 2100,
      smartphones: 950,
      tablets: 250,
      total: 4800,
    },
  },
  {
    name: 'Rio Grande do Sul',
    region: 'South',
    devices: {
      desktops: 1400,
      laptops: 2000,
      smartphones: 850,
      tablets: 250,
      total: 4500,
    },
  },
  {
    name: 'Santa Catarina',
    region: 'South',
    devices: {
      desktops: 1300,
      laptops: 1900,
      smartphones: 800,
      tablets: 200,
      total: 4200,
    },
  },
  {
    name: 'Pernambuco',
    region: 'Northeast',
    devices: {
      desktops: 1100,
      laptops: 1600,
      smartphones: 800,
      tablets: 300,
      total: 3800,
    },
  },
  {
    name: 'Ceará',
    region: 'Northeast',
    devices: {
      desktops: 1100,
      laptops: 1600,
      smartphones: 750,
      tablets: 250,
      total: 3700,
    },
  },
  {
    name: 'Pará',
    region: 'North',
    devices: {
      desktops: 1000,
      laptops: 1500,
      smartphones: 750,
      tablets: 250,
      total: 3500,
    },
  },
  {
    name: 'Goiás',
    region: 'Central-West',
    devices: {
      desktops: 1000,
      laptops: 1400,
      smartphones: 650,
      tablets: 250,
      total: 3300,
    },
  },
  {
    name: 'Maranhão',
    region: 'Northeast',
    devices: {
      desktops: 800,
      laptops: 1200,
      smartphones: 600,
      tablets: 200,
      total: 2800,
    },
  },
  {
    name: 'Distrito Federal',
    region: 'Central-West',
    devices: {
      desktops: 850,
      laptops: 1100,
      smartphones: 500,
      tablets: 150,
      total: 2600,
    },
  },
  {
    name: 'Amazonas',
    region: 'North',
    devices: {
      desktops: 600,
      laptops: 900,
      smartphones: 450,
      tablets: 150,
      total: 2100,
    },
  },
  {
    name: 'Espírito Santo',
    region: 'Southeast',
    devices: {
      desktops: 650,
      laptops: 850,
      smartphones: 400,
      tablets: 100,
      total: 2000,
    },
  },
  {
    name: 'Paraíba',
    region: 'Northeast',
    devices: {
      desktops: 550,
      laptops: 800,
      smartphones: 400,
      tablets: 150,
      total: 1900,
    },
  },
  {
    name: 'Mato Grosso',
    region: 'Central-West',
    devices: {
      desktops: 550,
      laptops: 800,
      smartphones: 350,
      tablets: 100,
      total: 1800,
    },
  },
  {
    name: 'Rio Grande do Norte',
    region: 'Northeast',
    devices: {
      desktops: 450,
      laptops: 700,
      smartphones: 350,
      tablets: 100,
      total: 1600,
    },
  },
  {
    name: 'Piauí',
    region: 'Northeast',
    devices: {
      desktops: 450,
      laptops: 650,
      smartphones: 300,
      tablets: 100,
      total: 1500,
    },
  },
  {
    name: 'Alagoas',
    region: 'Northeast',
    devices: {
      desktops: 450,
      laptops: 650,
      smartphones: 300,
      tablets: 100,
      total: 1500,
    },
  },
  {
    name: 'Mato Grosso do Sul',
    region: 'Central-West',
    devices: {
      desktops: 450,
      laptops: 600,
      smartphones: 280,
      tablets: 70,
      total: 1400,
    },
  },
  {
    name: 'Sergipe',
    region: 'Northeast',
    devices: {
      desktops: 350,
      laptops: 500,
      smartphones: 200,
      tablets: 50,
      total: 1100,
    },
  },
  {
    name: 'Rondônia',
    region: 'North',
    devices: {
      desktops: 250,
      laptops: 400,
      smartphones: 180,
      tablets: 70,
      total: 900,
    },
  },
  {
    name: 'Tocantins',
    region: 'North',
    devices: {
      desktops: 220,
      laptops: 350,
      smartphones: 170,
      tablets: 60,
      total: 800,
    },
  },
  {
    name: 'Acre',
    region: 'North',
    devices: {
      desktops: 140,
      laptops: 220,
      smartphones: 100,
      tablets: 40,
      total: 500,
    },
  },
  {
    name: 'Amapá',
    region: 'North',
    devices: {
      desktops: 120,
      laptops: 200,
      smartphones: 90,
      tablets: 40,
      total: 450,
    },
  },
  {
    name: 'Roraima',
    region: 'North',
    devices: {
      desktops: 110,
      laptops: 180,
      smartphones: 80,
      tablets: 30,
      total: 400,
    },
  },
];
